### ISSUE TITLE
warning in build_cc

### ISSUE THREAD

**Issue by ryancinsight** [SchrodingerZhu/snmalloc-rs#133]
@mjp41 saw new warning in updates to snmalloc using gcc, should I add any flags as suggested below in warning.

warning: In file included from snmalloc/src/override/../mem/slab.h:3,
warning:                  from snmalloc/src/override/../mem/chunkmap.h:9,
warning:                  from snmalloc/src/override/../mem/alloc.h:11,
warning:                  from snmalloc/src/override/../mem/globalalloc.h:4,
warning:                  from snmalloc/src/override/../mem/slowalloc.h:3,
warning:                  from snmalloc/src/override/malloc.cc:1,
warning:                  from snmalloc/src/override/rust.cc:2:
warning: snmalloc/src/override/../mem/freelist.h: In member function ‘void* snmalloc::Allocator<NeedsInitialisation, InitThreadAllocator, MemoryProvider, ChunkMap, IsQueueInline>::small_alloc_new_slab(snmalloc::sizeclass_t) [with snmalloc::ZeroMem zero_mem = snmalloc::NoZero; bool (* NeedsInitialisation)(void*) = snmalloc::needs_initialisation; void* (* InitThreadAllocator)(snmalloc::function_ref<void*(void*)>) = snmalloc::init_thread_allocator; MemoryProvider = snmalloc::MemoryProviderStateMixin<snmalloc::PALLinux>; ChunkMap = snmalloc::DefaultChunkMap<>; bool IsQueueInline = true]’:
warning: snmalloc/src/override/../mem/freelist.h:120:20: warning: ‘b.snmalloc::FreeListBuilder<unsigned int>::head[1].snmalloc::EncodeFreeObjectReference::reference’ may be used uninitialized in this function [-Wmaybe-uninitialized]
warning:   120 |       return encode(local_key, reference);
warning:       |              ~~~~~~^~~~~~~~~~~~~~~~~~~~~~
warning: snmalloc/src/override/../mem/freelist.h: In member function ‘void* snmalloc::Allocator<NeedsInitialisation, InitThreadAllocator, MemoryProvider, ChunkMap, IsQueueInline>::small_alloc_new_slab(snmalloc::sizeclass_t) [with snmalloc::ZeroMem zero_mem = snmalloc::YesZero; bool (* NeedsInitialisation)(void*) = snmalloc::needs_initialisation; void* (* InitThreadAllocator)(snmalloc::function_ref<void*(void*)>) = snmalloc::init_thread_allocator; MemoryProvider = snmalloc::MemoryProviderStateMixin<snmalloc::PALLinux>; ChunkMap = snmalloc::DefaultChunkMap<>; bool IsQueueInline = true]’:
warning: snmalloc/src/override/../mem/freelist.h:120:20: warning: ‘b.snmalloc::FreeListBuilder<unsigned int>::head[1].snmalloc::EncodeFreeObjectReference::reference’ may be used uninitialized in this function [-Wmaybe-uninitialized]
warning:   120 |       return encode(local_key, reference);
warning:       |              ~~~~~~^~~~~~~~~~~~~~~~~~~~~~
warning: snmalloc/src/override/../mem/freelist.h: In member function ‘void* snmalloc::Allocator<NeedsInitialisation, InitThreadAllocator, MemoryProvider, ChunkMap, IsQueueInline>::small_alloc_rare(snmalloc::sizeclass_t, size_t) [with snmalloc::ZeroMem zero_mem = snmalloc::YesZero; bool (* NeedsInitialisation)(void*) = snmalloc::needs_initialisation; void* (* InitThreadAllocator)(snmalloc::function_ref<void*(void*)>) = snmalloc::init_thread_allocator; MemoryProvider = snmalloc::MemoryProviderStateMixin<snmalloc::PALLinux>; ChunkMap = snmalloc::DefaultChunkMap<>; bool IsQueueInline = true]’:
warning: snmalloc/src/override/../mem/freelist.h:120:20: warning: ‘b.snmalloc::FreeListBuilder<unsigned int>::head[1].snmalloc::EncodeFreeObjectReference::reference’ may be used uninitialized in this function [-Wmaybe-uninitialized]
warning:   120 |       return encode(local_key, reference);
warning:       |              ~~~~~~^~~~~~~~~~~~~~~~~~~~~~
warning: snmalloc/src/override/../mem/freelist.h: In member function ‘void* snmalloc::Allocator<NeedsInitialisation, InitThreadAllocator, MemoryProvider, ChunkMap, IsQueueInline>::small_alloc_rare(snmalloc::sizeclass_t, size_t) [with snmalloc::ZeroMem zero_mem = snmalloc::NoZero; bool (* NeedsInitialisation)(void*) = snmalloc::needs_initialisation; void* (* InitThreadAllocator)(snmalloc::function_ref<void*(void*)>) = snmalloc::init_thread_allocator; MemoryProvider = snmalloc::MemoryProviderStateMixin<snmalloc::PALLinux>; ChunkMap = snmalloc::DefaultChunkMap<>; bool IsQueueInline = true]’:
warning: snmalloc/src/override/../mem/freelist.h:120:20: warning: ‘b.snmalloc::FreeListBuilder<unsigned int>::head[1].snmalloc::EncodeFreeObjectReference::reference’ may be used uninitialized in this function [-Wmaybe-uninitialized]
warning:   120 |       return encode(local_key, reference);
warning:       |              ~~~~~~^~~~~~~~~~~~~~~~~~~~~~

**Comment by ryancinsight** [comment]
Seems to only be in Ubuntu, windows and mac have no warnings

**Comment by mjp41** [comment]
I don't like disabling warnings.  But GCC can be quite aggressive in its complaints.  I can't see from the information enough about why it thinks it is uninitialised.  Given the code is effectively signing things, uninitialised memory would have a 1/(2^48) of not being caught.  I think it is spurious.

If you disable the warning, can you make it only disabled on GCC, and not on clang.

**Comment by ryancinsight** [comment]
I'm ok with it, but I'll make sure to make sure clang warnings don't get disabled if I change anything in future.
