### ISSUE TITLE
Use libc++ on Mac OS X

### ISSUE THREAD

**Issue by mjp41** [SchrodingerZhu/snmalloc-rs#17]
Could we change to using libc++ on Mac OS X.  The current crate does not work on Catalina.

I think we just need to add another option here:
https://github.com/SchrodingerZhu/snmalloc-rs/blob/a358c33f2fa4715d4899949f1bd879db8c820b80/snmalloc-sys/build.rs#L40

I guess this would change to 
```C
 println!("cargo:rustc-link-lib=dylib=c++"); 
```
on Mac OS X.

**Comment by plietar** [comment]
Just to confirm I have the same issue on Catalina, but I'm able to build by applying the suggested change. The `cc` crate has a piece of logic that selects the right stdlib, ie. libc++ on darwin/bsd, libstdc++ elsewhere: https://github.com/alexcrichton/cc-rs/blob/master/src/lib.rs#L2248-L2259. I think the same rules should be used here.

**Comment by SchrodingerZhu** [comment]
fixed #18 .

**Comment by SchrodingerZhu** [comment]
Yet, the crate failed to compile on MinGW. 
And BSD environment is not tested yet.

**Comment by SchrodingerZhu** [comment]
`freebsd` works well

**Comment by SchrodingerZhu** [comment]
I will close this then and open a new issue for `mingw`
