### ISSUE TITLE
Automating keeping snmalloc up to date.

### ISSUE THREAD

**Issue by mjp41** [SchrodingerZhu/snmalloc-rs#3]
For Project Verona @plietar built a github action that automatically raises an issue if the snmalloc submodule is out of date.  This might be useful for this project too:

https://github.com/microsoft/verona/blob/master/.github/workflows/update-snmalloc.yaml

**Comment by outloudvi** [comment]
Dependabot may have your back: https://dependabot.com/submodules/ .
A random PR sample: osyrisrblx/t#37

**Comment by SchrodingerZhu** [comment]
I added a Dependabot to watch over the rust crates and git submodules at the same time.
