### ISSUE TITLE
Change the `if` statement in `snmalloc-sys/build.rs` to be more futureproof

### ISSUE THREAD

**Issue by mzji** [SchrodingerZhu/snmalloc-rs#4]
https://github.com/SchrodingerZhu/snmalloc-rs/blob/089d2988f8fecc2afb52ed8d3f45fc99eef0e2b3/snmalloc-sys/build.rs#L30-L36

This `if` statement should be changed to like the following:

```rust
    if cfg!(windows) {
        println!("cargo:rustc-link-search=native={}/{}", dst.display(), build_type);
        println!("cargo:rustc-link-lib=dylib=mincore");
    } else {
        println!("cargo:rustc-link-search=native={}", dst.display());
        println!("cargo:rustc-link-lib=dylib=stdc++");
    }
```

Since only windows targets have the `mincore` library.

**Comment by SchrodingerZhu** [comment]
I think it is a good idea. will change it in a later commit.
